### ISSUE TITLE
Make some dependencies optional

### ISSUE THREAD

**Issue by jarmitage** [afhverjuekki/tolvera#43]
Of these: https://github.com/afhverjuekki/tolvera/blob/main/pyproject.toml#L12

Probably these could be made optional:
```toml
opencv-python = "^4.8.1.78"
iipyper = "^0.1.0b1"
anguilla-iml = "0.3.0"
mediapipe = "0.10.20"
dualsense-controller = "^0.2.0"
```

This would aid with compatibility, specifically for Intel Macs.

Separate issue, but these could also be removed later or also made optional:
```toml
sardine = "^0.0.0b3"
torch = "^2.2.2"
```
